# Generated by Django 3.2 on 2021-04-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_costumer_order_custumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custumer',
            new_name='costumer',
        ),
    ]
